#!/usr/bin/env node
/*
 * build.js -- inline index.html, src/styles.css and the src/*.js modules into a
 * single self-contained page.
 *
 * The result has no external references at all, so it can be emailed, dropped
 * on a share or opened straight from disk on a machine with no network.
 *
 *   node tools/build.js
 */
'use strict';

const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const out = path.join(root, 'abaqus-inp-editor.html');

function read(rel) {
  return fs.readFileSync(path.join(root, rel), 'utf8');
}

let html = read('index.html');

/* Inline the stylesheet. */
html = html.replace(
  /<link rel="stylesheet" href="src\/styles\.css">/,
  () => '<style>\n' + read('src/styles.css').trimEnd() + '\n</style>'
);

/* Inline each script in the order the page lists them. */
html = html.replace(/<script src="(src\/[^"]+)"><\/script>/g, (_, rel) => {
  const code = read(rel).trimEnd();
  /* A literal </script> inside a JS string would end the block early. */
  const safe = code.replace(/<\/script>/gi, '<\\/script>');
  return '<script>\n/* ===== ' + rel + ' ===== */\n' + safe + '\n</script>';
});

if (/<script src=|<link rel="stylesheet"/.test(html)) {
  console.error('build: some assets were not inlined');
  process.exit(1);
}

const banner = '<!--\n  Abaqus INP Editor - single-file build\n' +
  '  Generated by tools/build.js on ' + new Date().toISOString().slice(0, 10) + '\n' +
  '  Source: index.html + src/*.js + src/styles.css\n-->\n';
html = html.replace(/^<!DOCTYPE html>\n/, '<!DOCTYPE html>\n' + banner);

fs.writeFileSync(out, html);
const kb = (Buffer.byteLength(html) / 1024).toFixed(0);
console.log('wrote ' + path.relative(root, out) + ' (' + kb + ' KB)');
