from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List

from .cad import metadata_index
from .names import abaqus_name, prefixed, safe_filename
from .project import ELEMENT_TYPES


def _v(v: Any) -> str:
    """Abaqus DisplacementBC value: blank means 'leave this DOF unconstrained'."""
    if v is None or v == "":
        return "UNSET"
    return repr(float(v))


def _element_type(project: Dict[str, Any]) -> str:
    """Whitelisted element code.

    The value is interpolated straight into the generated Python as an
    abaqusConstants symbol, so it must never be free text from the request.
    """
    solver = project.get("analysis", {}).get("solver", "standard")
    allowed = ELEMENT_TYPES.get(solver, ELEMENT_TYPES["standard"])
    requested = str(project.get("mesh", {}).get("element_type", "")).strip().upper()
    return requested if requested in allowed else allowed[0]


def _set_points(project: Dict[str, Any]) -> Dict[str, Dict[str, Any]]:
    """Map each set to the witness points Abaqus uses to re-find its geometry.

    Keys are Abaqus-legal names, and every reference elsewhere in this module is
    sanitised the same way, so a set called "Tread Contact" is created and
    referenced as TREAD-safe "Tread_Contact" consistently.
    """
    idx = metadata_index(project["cad_metadata"])
    out: Dict[str, Dict[str, Any]] = {}
    for s in project.get("sets", []):
        kind = s.get("kind")
        points = []
        for entity_id in s.get("entity_ids", []):
            item = idx.get(entity_id)
            if not item:
                continue
            if kind == "edge":
                points.append(item["midpoint"])
            else:
                points.append(item.get("witness", item["center"]))
        out[abaqus_name(s["name"])] = {"kind": kind, "points": points}
    return out


def _steps(project: Dict[str, Any]) -> List[Dict[str, Any]]:
    steps = project.get("steps") or []
    if steps:
        return steps
    a = project.get("analysis", {})
    return [{
        "name": a.get("step_name", "Load"), "type": "static", "time_period": a.get("time_period", 1.0),
        "nlgeom": a.get("nlgeom", True), "initial_increment": a.get("initial_increment", 0.01),
        "min_increment": a.get("min_increment", 1e-8), "max_increment": a.get("max_increment", 0.1),
        "max_increments": a.get("max_increments", 1000),
    }]


def _contact_property(add, created: set, prop: str, mu: float) -> None:
    """Emit a contact property once; re-creating the same name aborts Abaqus."""
    if prop in created:
        return
    created.add(prop)
    add(f"model.ContactProperty({prop!r})")
    add(f"model.interactionProperties[{prop!r}].TangentialBehavior(formulation=PENALTY, directionality=ISOTROPIC, "
        f"slipRateDependency=OFF, pressureDependency=OFF, temperatureDependency=OFF, dependencies=0, "
        f"table=(({mu!r},),), shearStressLimit=None, maximumElasticSlip=FRACTION, fraction=0.005, "
        f"elasticSlipStiffness=None)")
    add(f"model.interactionProperties[{prop!r}].NormalBehavior(pressureOverclosure=HARD, allowSeparation=ON, "
        f"constraintEnforcementMethod=DEFAULT)")


def generate_build_script(project: Dict[str, Any], step_path: Path, case_dir: Path) -> str:
    model = project.get("model", {})
    analysis = project.get("analysis", {})
    mesh_cfg = project.get("mesh", {})
    road = project.get("road") or {}
    matlib = project.get("material_library") or {}
    steps = _steps(project)
    sets = _set_points(project)

    job_name = abaqus_name(analysis.get("job_name", "AutoJob"), "J")
    model_name = abaqus_name(model.get("model_name", "Model-1"), "M")
    part_name = abaqus_name(model.get("part_name", "ImportedPart"), "P")
    instance_name = abaqus_name(model.get("instance_name", "IMPORTEDPART-1"), "I")
    first_step = abaqus_name(steps[0].get("name", "Load"), "Step")
    is_explicit = analysis.get("solver", "standard") == "explicit"

    include_name = Path(str(matlib.get("local_include_name") or matlib.get("uploaded_name") or "materials.inc")).name
    material_password = str(matlib.get("password") or "")
    material_code = str(matlib.get("material_code") or "").strip()
    material_body_set = abaqus_name(matlib.get("body_set") or "TREAD_BODY")

    lines: List[str] = []
    add = lines.append
    add("# Auto-generated by STEP -> Abaqus Automation Platform v0.7")
    add("from abaqus import *")
    add("from abaqusConstants import *")
    add("import mesh, os, re, sys, traceback")
    add("")
    add(f"STEP_FILE = r{str(step_path)!r}")
    add(f"WORK_DIR = r{str(case_dir)!r}")
    add(f"MODEL_NAME = {model_name!r}")
    add(f"PART_NAME = {part_name!r}")
    add(f"INSTANCE_NAME = {instance_name!r}")
    add(f"JOB_NAME = {job_name!r}")
    add(f"SET_DEFS = {json.dumps(sets, indent=2)}")
    add(f"MATERIAL_INCLUDE = {include_name!r}")
    add(f"MATERIAL_PASSWORD = {material_password!r}")
    add(f"MATERIAL_CODE = {material_code!r}")
    add(f"MATERIAL_BODY_SET = {material_body_set!r}")
    add("os.chdir(WORK_DIR)")
    add("")
    add("def _find_one(seq, pt):")
    add("    q = tuple(float(x) for x in pt)")
    add("    for fn in (lambda: seq.findAt((q,)), lambda: seq.findAt(q)):")
    add("        try:")
    add("            obj = fn()")
    add("            try:")
    add("                if len(obj) == 1: return obj[0]")
    add("            except Exception: pass")
    add("            return obj")
    add("        except Exception: pass")
    add("    try:")
    add("        d = seq.getClosest(coordinates=(q,))")
    add("        if 0 in d: return d[0][0]")
    add("    except Exception: pass")
    add("    raise RuntimeError('Could not match imported entity at %s' % (q,))")
    add("")
    add("def _contact_pair(name, main_surface, secondary_surface, prop, explicit):")
    add("    # Abaqus 2020 renamed master/slave to main/secondary. Try the current")
    add("    # spelling first so the script works on both old and new releases.")
    add("    kw = dict(name=name, createStepName='Initial', interactionProperty=prop, sliding=FINITE)")
    add("    maker = model.SurfaceToSurfaceContactExp if explicit else model.SurfaceToSurfaceContactStd")
    add("    if explicit: kw['mechanicalConstraint'] = KINEMATIC")
    add("    else: kw.update(adjustMethod=NONE, initialClearance=OMIT, datumAxis=None, clearanceRegion=None)")
    add("    try:")
    add("        return maker(main=main_surface, secondary=secondary_surface, **kw)")
    add("    except Exception:")
    add("        return maker(master=main_surface, slave=secondary_surface, **kw)")
    add("")
    add("def _inject_material_library(inp_path):")
    add("    # Geometry, mesh and sets come from CAE; the constitutive data come from")
    add("    # the external encrypted include library, so the section assignment and")
    add("    # the *Include line are written into the INP after CAE has produced it.")
    add("    f = open(inp_path, 'r')")
    add("    try: lines = f.readlines()")
    add("    finally: f.close()")
    add("    out = []; in_target_part = False; section_inserted = False; include_inserted = False")
    add("    part_pat = re.compile(r'^\\s*\\*Part\\s*,.*\\bname\\s*=\\s*([^,\\r\\n]+)', re.I)")
    add("    for line in lines:")
    add("        low = line.strip().lower()")
    add("        m = part_pat.match(line)")
    add("        if m:")
    add("            pname = m.group(1).strip().strip(chr(34)).strip(chr(39))")
    add("            in_target_part = (pname.upper() == PART_NAME.upper())")
    add("        if in_target_part and low.startswith('*end part') and not section_inserted:")
    add("            out.append('** SECTION ASSIGNMENT FROM EXTERNAL MATERIAL LIBRARY\\n')")
    add("            out.append('*Solid Section, elset=%s, material=%s\\n' % (MATERIAL_BODY_SET, MATERIAL_CODE))")
    add("            out.append(',\\n')")
    add("            section_inserted = True")
    add("        out.append(line)")
    add("        if low.startswith('*end assembly') and not include_inserted:")
    add("            inc = '*Include, input=%s' % MATERIAL_INCLUDE")
    add("            if MATERIAL_PASSWORD: inc += ', PASSWORD=%s' % MATERIAL_PASSWORD")
    add("            out.append('** EXTERNAL HYPERELASTIC MATERIAL LIBRARY\\n')")
    add("            out.append(inc + '\\n')")
    add("            include_inserted = True")
    add("    if not section_inserted:")
    add("        raise RuntimeError('Could not insert a solid section for element set %s in part %s. '")
    add("                           'Check that the body set exists.' % (MATERIAL_BODY_SET, PART_NAME))")
    add("    if not include_inserted:")
    add("        raise RuntimeError('Could not find *End Assembly while inserting the material include.')")
    add("    f = open(inp_path, 'w')")
    add("    try: f.writelines(out)")
    add("    finally: f.close()")
    add("    print('MATERIAL_LIBRARY_APPLIED %s %s' % (MATERIAL_CODE, MATERIAL_INCLUDE))")
    add("")
    add("try:")
    body: List[str] = []
    badd = body.append

    badd("if MODEL_NAME in mdb.models: del mdb.models[MODEL_NAME]")
    badd("model = mdb.Model(name=MODEL_NAME)")
    badd("geom = mdb.openStep(STEP_FILE, scaleFromFile=OFF)")
    badd("p = model.PartFromGeometryFile(name=PART_NAME, geometryFile=geom, combine=True, "
         "dimensionality=THREE_D, type=DEFORMABLE_BODY)")
    badd("if not len(p.cells):")
    badd("    raise RuntimeError('The imported STEP produced no solid cells. A solid body is required "
         "for a tetrahedral mesh; check the STEP export.')")
    badd("")
    badd("# Re-create CAD sets from geometric witness points rather than face numbers.")
    badd("for raw_name, spec in SET_DEFS.items():")
    badd("    pts = spec['points']")
    badd("    if not pts: continue")
    badd("    kind = spec['kind']")
    badd("    if kind == 'face': p.Set(name=raw_name, faces=tuple(_find_one(p.faces, q) for q in pts))")
    badd("    elif kind == 'edge': p.Set(name=raw_name, edges=tuple(_find_one(p.edges, q) for q in pts))")
    badd("    elif kind == 'body': p.Set(name=raw_name, cells=tuple(_find_one(p.cells, q) for q in pts))")
    badd("")

    # Mesh
    size = float(mesh_cfg.get("global_size", 2.0) or 2.0)
    elem = _element_type(project)
    elem_lib = "EXPLICIT" if is_explicit else "STANDARD"
    badd(f"p.seedPart(size={size!r}, deviationFactor=0.1, minSizeFactor=0.1)")
    badd("p.setMeshControls(regions=p.cells, elemShape=TET, technique=FREE)")
    badd(f"elemType1 = mesh.ElemType(elemCode={elem}, elemLibrary={elem_lib})")
    badd("p.setElementType(regions=(p.cells,), elemTypes=(elemType1,))")
    badd("p.generateMesh()")
    badd("if not len(p.elements): raise RuntimeError('Meshing produced no elements; try a smaller global size.')")
    badd("")
    badd("# Nodal equivalents of the CAD face sets, for post-processing.")
    badd("for raw_name, spec in SET_DEFS.items():")
    badd("    if spec['kind'] != 'face' or raw_name not in p.sets: continue")
    badd("    nodes = []; seen = set()")
    badd("    for f in p.sets[raw_name].faces:")
    badd("        try: fnodes = f.getNodes()")
    badd("        except Exception: fnodes = []")
    badd("        for n in fnodes:")
    badd("            if n.label not in seen: seen.add(n.label); nodes.append(n)")
    badd("    if nodes: p.Set(name='N_' + raw_name, nodes=tuple(nodes))")
    badd("")
    badd("a = model.rootAssembly")
    badd("a.DatumCsysByDefault(CARTESIAN)")
    badd(f"inst = a.Instance(name={instance_name!r}, part=p, dependent=ON)")
    badd("")

    # Surfaces for every face set
    for s in project.get("sets", []):
        if s.get("kind") != "face":
            continue
        safe = abaqus_name(s["name"])
        badd(f"a.Surface(name={prefixed('SURF_', s['name'])!r}, side1Faces=inst.sets[{safe!r}].faces)")
    badd("")

    created_props: set = set()

    # Analytical rigid road
    if road.get("enabled"):
        length = float(road.get("length", 100.0) or 100.0)
        width = float(road.get("width", 100.0) or 100.0)
        cx = float(road.get("center_x", 0.0) or 0.0)
        cy = float(road.get("center_y", 0.0) or 0.0)
        cz = float(road.get("center_z", 0.0) or 0.0)
        normal_axis = str(road.get("normal_axis", "Y")).upper()
        normal_sign = -1 if str(road.get("normal_sign", "+")).startswith("-") else 1
        badd("# Analytical rigid road: a line sketched in X-Y, extruded along Z.")
        badd(f"sk = model.ConstrainedSketch(name='__ROAD_PROFILE__', sheetSize={max(length, width) * 4.0!r})")
        badd(f"sk.Line(point1=({-length / 2.0!r}, 0.0), point2=({length / 2.0!r}, 0.0))")
        badd("roadPart = model.Part(name='ROAD', dimensionality=THREE_D, type=ANALYTIC_RIGID_SURFACE)")
        badd(f"roadPart.AnalyticRigidSurfExtrude(sketch=sk, depth={width!r})")
        badd("# Releases differ in whether the extrusion runs along +Z or -Z, so read")
        badd("# the sign off the created surface instead of assuming it.")
        badd("_zs = []")
        badd("for _f in roadPart.faces:")
        badd("    try: _zs.append(_f.pointOn[0][2])")
        badd("    except Exception: pass")
        badd("_sgn = -1.0 if (_zs and sum(_zs) / len(_zs) < 0.0) else 1.0")
        badd(f"_half = _sgn * {width / 2.0!r}")
        badd("roadRPFeat = roadPart.ReferencePoint(point=(0.0, 0.0, _half))")
        badd("roadInst = a.Instance(name='ROAD-1', part=roadPart, dependent=ON)")
        if normal_axis == "X":
            badd("a.rotate(instanceList=('ROAD-1',), axisPoint=(0.0,0.0,0.0), axisDirection=(0.0,0.0,1.0), angle=-90.0)")
            badd("_src = (0.0, 0.0, _half)")
        elif normal_axis == "Z":
            badd("a.rotate(instanceList=('ROAD-1',), axisPoint=(0.0,0.0,0.0), axisDirection=(1.0,0.0,0.0), angle=90.0)")
            badd("_src = (0.0, -_half, 0.0)")
        else:
            badd("_src = (0.0, 0.0, _half)")
        badd(f"a.translate(instanceList=('ROAD-1',), vector=({cx!r} - _src[0], {cy!r} - _src[1], {cz!r} - _src[2]))")
        side_kw = "side2Faces" if normal_sign < 0 else "side1Faces"
        badd(f"a.Surface(name='ROAD_SURFACE', {side_kw}=roadInst.faces)")
        badd("roadRP = roadInst.referencePoints[roadRPFeat.id]")
        badd("a.Set(name='RP_ROAD', referencePoints=(roadRP,))")
        mu = float(road.get("friction", 0.8) or 0.0)
        _contact_property(badd, created_props, "PROP_ROAD_CONTACT", mu)
        slave = prefixed("SURF_", road.get("contact_set", ""))
        badd(f"_contact_pair('TREAD_ROAD_CONTACT', a.surfaces['ROAD_SURFACE'], a.surfaces[{slave!r}], "
             f"'PROP_ROAD_CONTACT', {is_explicit!r})")
        badd("")

    # Steps
    previous = "Initial"
    for st in steps:
        sn = abaqus_name(st.get("name", "Step"), "Step")
        tp = float(st.get("time_period", 1.0) or 1.0)
        if is_explicit:
            badd(f"model.ExplicitDynamicsStep(name={sn!r}, previous={previous!r}, timePeriod={tp!r})")
        else:
            nl = "ON" if st.get("nlgeom", analysis.get("nlgeom", True)) else "OFF"
            ii = float(st.get("initial_increment", 0.01) or 0.01)
            mi = float(st.get("min_increment", 1e-8) or 1e-8)
            ma = float(st.get("max_increment", 0.1) or 0.1)
            mx = int(st.get("max_increments", 1000) or 1000)
            badd(f"model.StaticStep(name={sn!r}, previous={previous!r}, timePeriod={tp!r}, nlgeom={nl}, "
                 f"initialInc={ii!r}, maxInc={ma!r}, minInc={mi!r}, maxNumInc={mx})")
            if st.get("stabilization") not in (None, "", 0, 0.0):
                sf = float(st["stabilization"])
                badd(f"model.steps[{sn!r}].setValues(stabilizationMethod=DISSIPATED_ENERGY_FRACTION, "
                     f"stabilizationMagnitude={sf!r}, adaptiveDampingRatio=0.05)")
        previous = sn
    badd("")

    # Reference points and couplings
    for ri, rp in enumerate(project.get("reference_points", []), 1):
        rn = abaqus_name(rp.get("name", f"RP_{ri}"), "RP")
        xyz = tuple(float(rp.get(k, 0.0) or 0.0) for k in ("x", "y", "z"))
        badd(f"feat = a.ReferencePoint(point={xyz!r})")
        badd(f"a.Set(name={rn!r}, referencePoints=(a.referencePoints[feat.id],))")
        target = rp.get("coupled_surface")
        if target:
            badd(f"model.Coupling(name={prefixed('COUP_', rn)!r}, controlPoint=a.sets[{rn!r}], "
                 f"surface=a.surfaces[{prefixed('SURF_', target)!r}], influenceRadius=WHOLE_SURFACE, "
                 f"couplingType=KINEMATIC, localCsys=None, u1=ON, u2=ON, u3=ON, ur1=ON, ur2=ON, ur3=ON)")
    badd("")

    # Pair contacts
    for ii, inter in enumerate(project.get("interactions", []), 1):
        iname = abaqus_name(inter.get("name", f"Contact_{ii}"), "INT")
        prop = prefixed("PROP_", iname)
        _contact_property(badd, created_props, prop, float(inter.get("friction", 0.0) or 0.0))
        master = prefixed("SURF_", inter.get("master_set", ""))
        slave = prefixed("SURF_", inter.get("slave_set", ""))
        badd(f"_contact_pair({iname!r}, a.surfaces[{master!r}], a.surfaces[{slave!r}], {prop!r}, {is_explicit!r})")
    badd("")

    # Sipe self-contact, one definition per detected sipe.
    for ii, sc in enumerate(project.get("self_contacts", []), 1):
        name = abaqus_name(sc.get("name", f"SelfContact_{ii}"), "SELF")
        prop = prefixed("PROP_", name)
        _contact_property(badd, created_props, prop, float(sc.get("friction", 0.0) or 0.0))
        surf = prefixed("SURF_", sc.get("surface_set", ""))
        if is_explicit:
            badd(f"model.SelfContactExp(name={name!r}, createStepName='Initial', surface=a.surfaces[{surf!r}], "
                 f"mechanicalConstraint=KINEMATIC, interactionProperty={prop!r})")
        else:
            badd(f"model.SelfContactStd(name={name!r}, createStepName='Initial', surface=a.surfaces[{surf!r}], "
                 f"interactionProperty={prop!r}, enforcement=SURFACE_TO_SURFACE, thickness=ON)")
    badd("")

    # Boundary conditions
    for bi, bc in enumerate(project.get("boundary_conditions", []), 1):
        bn = abaqus_name(bc.get("name", f"BC_{bi}"), "BC")
        sn = abaqus_name(bc.get("step") or steps[0].get("name", "Load"), "Step")
        if bc.get("operation", "create") == "modify":
            target = abaqus_name(bc.get("target_bc") or bc.get("name", ""), "BC")
            kwargs = [f"{k}={float(bc[k])!r}" for k in ("u1", "u2", "u3", "ur1", "ur2", "ur3")
                      if bc.get(k) not in (None, "")]
            tail = (", " + ", ".join(kwargs)) if kwargs else ""
            badd(f"model.boundaryConditions[{target!r}].setValuesInStep(stepName={sn!r}{tail})")
            continue
        region = abaqus_name(bc.get("region", ""))
        regexpr = f"a.sets[{region!r}]" if bc.get("region_type") == "rp" else f"inst.sets[{region!r}]"
        vals = [_v(bc.get(k)) for k in ("u1", "u2", "u3", "ur1", "ur2", "ur3")]
        badd(f"model.DisplacementBC(name={bn!r}, createStepName={sn!r}, region={regexpr}, "
             f"u1={vals[0]}, u2={vals[1]}, u3={vals[2]}, ur1={vals[3]}, ur2={vals[4]}, ur3={vals[5]}, "
             f"amplitude=UNSET, distributionType=UNIFORM, fieldName='', localCsys=None)")
    badd("")

    # Loads
    for li, load in enumerate(project.get("loads", []), 1):
        ln = abaqus_name(load.get("name", f"Load_{li}"), "L")
        sn = abaqus_name(load.get("step") or steps[0].get("name", "Load"), "Step")
        ltype = load.get("type", "pressure")
        if ltype == "pressure":
            surf = prefixed("SURF_", load.get("region", ""))
            badd(f"model.Pressure(name={ln!r}, createStepName={sn!r}, region=a.surfaces[{surf!r}], "
                 f"magnitude={float(load.get('magnitude', 0.0) or 0.0)!r})")
        elif ltype == "force":
            rn = abaqus_name(load.get("region", ""))
            badd(f"model.ConcentratedForce(name={ln!r}, createStepName={sn!r}, region=a.sets[{rn!r}], "
                 f"cf1={float(load.get('f1', 0.0) or 0.0)!r}, cf2={float(load.get('f2', 0.0) or 0.0)!r}, "
                 f"cf3={float(load.get('f3', 0.0) or 0.0)!r})")
        elif ltype == "moment":
            rn = abaqus_name(load.get("region", ""))
            badd(f"model.Moment(name={ln!r}, createStepName={sn!r}, region=a.sets[{rn!r}], "
                 f"cm1={float(load.get('m1', 0.0) or 0.0)!r}, cm2={float(load.get('m2', 0.0) or 0.0)!r}, "
                 f"cm3={float(load.get('m3', 0.0) or 0.0)!r})")
    badd("")

    # Output requests.  Explicit steps write every increment under frequency=1,
    # which produces an unusable ODB, so intervals are used there instead.
    vars_tuple = tuple(str(x).upper() for x in (analysis.get("field_variables") or ["S", "U", "RF", "LE"]) if x)
    out_kw = "numIntervals=20" if is_explicit else "frequency=1"
    badd("try: del model.fieldOutputRequests['F-Output-1']")
    badd("except Exception: pass")
    badd(f"model.FieldOutputRequest(name='F-Output-1', createStepName={first_step!r}, "
         f"variables={vars_tuple!r}, {out_kw})")
    badd("")
    rp_names = [abaqus_name(r.get("name", f"RP_{i}"), "RP")
                for i, r in enumerate(project.get("reference_points", []), 1)]
    if road.get("enabled"):
        rp_names.append("RP_ROAD")
    hist_vars = ("U1", "U2", "U3", "UR1", "UR2", "UR3", "RF1", "RF2", "RF3", "RM1", "RM2", "RM3")
    for rn in rp_names:
        badd(f"try: model.HistoryOutputRequest(name={prefixed('H_', rn)!r}, createStepName={first_step!r}, "
             f"variables={hist_vars!r}, region=a.sets[{rn!r}], {out_kw})")
        badd("except Exception as e: print('WARNING_HISTORY_REQUEST %s' % str(e))")
    badd("")

    cpus = max(1, int(analysis.get("cpus", 4) or 1))
    badd(f"job = mdb.Job(name=JOB_NAME, model=MODEL_NAME, type=ANALYSIS, numCpus={cpus}, "
         f"numDomains={cpus}, multiprocessingMode=DEFAULT)")
    badd("job.writeInput(consistencyChecking=OFF)")
    badd("inp_path = os.path.join(WORK_DIR, JOB_NAME + '.inp')")
    badd("_inject_material_library(inp_path)")
    badd("del mdb.jobs[JOB_NAME]")
    badd("# Keep the CAE database so a failed run can be inspected interactively.")
    badd("try: mdb.saveAs(os.path.join(WORK_DIR, JOB_NAME + '.cae'))")
    badd("except Exception as e: print('WARNING_SAVE_CAE %s' % str(e))")
    badd(f"job = mdb.JobFromInputFile(name=JOB_NAME, inputFileName=inp_path, type=ANALYSIS, "
         f"numCpus={cpus}, multiprocessingMode=DEFAULT)")
    badd("job.submit()")
    badd("job.waitForCompletion()")
    badd("if job.status == ABORTED:")
    badd("    raise RuntimeError('The Abaqus job aborted. Check %s.msg and %s.dat.' % (JOB_NAME, JOB_NAME))")
    badd("print('AUTOMATION_JOB_COMPLETE %s' % JOB_NAME)")

    for line in body:
        add("    " + line if line else "")
    add("except Exception:")
    add("    traceback.print_exc()")
    add("    print('AUTOMATION_JOB_FAILED')")
    add("    sys.exit(1)")
    return "\n".join(lines) + "\n"


def generate_odb_script(project: Dict[str, Any], case_dir: Path) -> str:
    analysis = project.get("analysis", {})
    job_name = abaqus_name(analysis.get("job_name", "AutoJob"), "J")
    outputs = project.get("outputs") or [
        {"variable": "U", "region": "", "position": "NODAL"},
        {"variable": "S", "region": "", "position": "INTEGRATION_POINT"},
    ]
    # Region names must match the sanitised set names written into the ODB.
    resolved = [{
        "variable": str(o.get("variable", "")).upper(),
        "region": abaqus_name(o["region"]) if o.get("region") else "",
        "file_region": safe_filename(o.get("region") or "ALL"),
        "position": o.get("position", "NODAL"),
    } for o in outputs]

    return f'''# Auto-generated ODB -> CSV extractor v0.7
from odbAccess import openOdb
from abaqusConstants import *
import csv, os, sys, traceback

WORK_DIR = r{str(case_dir)!r}
ODB_PATH = os.path.join(WORK_DIR, {job_name!r} + '.odb')
OUTPUTS = {json.dumps(resolved, indent=2)}


def _open_csv(path):
    # Abaqus ships Python 2 up to the 2023 release and Python 3 from 2024.
    # Python 2 needs binary mode and Python 3 needs newline='' -- without this
    # every CSV written on Windows gains a blank line between rows.
    try:
        return open(path, 'w', newline='')
    except TypeError:
        return open(path, 'wb')


def _find_region(odb, name):
    if not name: return None
    candidates = [name, name.upper(), 'N_' + name, ('N_' + name).upper()]
    ra = odb.rootAssembly
    for n in candidates:
        if n in ra.nodeSets: return ra.nodeSets[n]
        if n in ra.elementSets: return ra.elementSets[n]
    for inst in ra.instances.values():
        for n in candidates:
            if n in inst.nodeSets: return inst.nodeSets[n]
            if n in inst.elementSets: return inst.elementSets[n]
    return None


def _const_position(name):
    return {{'NODAL': NODAL, 'ELEMENT_NODAL': ELEMENT_NODAL,
            'CENTROID': CENTROID, 'INTEGRATION_POINT': INTEGRATION_POINT}}.get(name)


def _as_list(data):
    try:
        return list(data)
    except Exception:
        return [data]


if not os.path.exists(ODB_PATH):
    print('ODB_EXTRACTION_FAILED the ODB was not found at %s' % ODB_PATH)
    sys.exit(1)

odb = openOdb(ODB_PATH, readOnly=True)
try:
    # 1) Every history output, for every step and region.
    f = _open_csv(os.path.join(WORK_DIR, 'History_All_Steps.csv'))
    try:
        w = csv.writer(f); w.writerow(['Step','Region','Variable','StepTime','Value'])
        for step_name, step in odb.steps.items():
            for region_name, region in step.historyRegions.items():
                for var, ho in region.historyOutputs.items():
                    for t, value in ho.data:
                        w.writerow([step_name, region_name, var, t, value])
    finally:
        f.close()

    # 2) Wide reference-point history table: one row per step/region/time.
    rp_vars = ['U1','U2','U3','UR1','UR2','UR3','RF1','RF2','RF3','RM1','RM2','RM3']
    f = _open_csv(os.path.join(WORK_DIR, 'RP_History_Wide.csv'))
    try:
        w = csv.writer(f); w.writerow(['Step','Region','StepTime'] + rp_vars)
        for step_name, step in odb.steps.items():
            for region_name, region in step.historyRegions.items():
                if not any(v in region.historyOutputs for v in rp_vars): continue
                times = set(); maps = {{}}
                for v in rp_vars:
                    if v in region.historyOutputs:
                        maps[v] = dict((float(t), value) for t, value in region.historyOutputs[v].data)
                        times.update(maps[v].keys())
                for t in sorted(times):
                    w.writerow([step_name, region_name, t] + [maps.get(v, {{}}).get(t, '') for v in rp_vars])
    finally:
        f.close()

    # 3) Global energy histories, when present.
    energy_vars = ['ALLAE','ALLCD','ALLDMD','ALLFD','ALLIE','ALLKE','ALLPD','ALLSE','ALLVD','ALLWK','ETOTAL']
    f = _open_csv(os.path.join(WORK_DIR, 'Energy_History.csv'))
    try:
        w = csv.writer(f); w.writerow(['Step','Region','Variable','StepTime','Value'])
        for step_name, step in odb.steps.items():
            for region_name, region in step.historyRegions.items():
                for v in energy_vars:
                    if v in region.historyOutputs:
                        for t, value in region.historyOutputs[v].data:
                            w.writerow([step_name, region_name, v, t, value])
    finally:
        f.close()

    # 4) Requested field outputs, for ALL steps and ALL frames.
    summary = []
    for spec in OUTPUTS:
        var = spec['variable']
        region_name = spec['region']
        out_name = '%s__%s__ALL_STEPS.csv' % (var, spec['file_region'])
        # Resolved once: the region does not change between frames.
        region = _find_region(odb, region_name)
        if region_name and region is None:
            summary.append([var, region_name, 'REGION_NOT_FOUND', 0, 0, out_name])
            continue
        pos = _const_position(spec['position'])
        total = 0; missing_frames = 0
        f = _open_csv(os.path.join(WORK_DIR, out_name))
        try:
            w = csv.writer(f); header_written = False
            for step_name, step in odb.steps.items():
                for frame_no, frame in enumerate(step.frames):
                    if var not in frame.fieldOutputs:
                        missing_frames += 1; continue
                    field = frame.fieldOutputs[var]
                    kwargs = {{}}
                    if region is not None: kwargs['region'] = region
                    if pos is not None: kwargs['position'] = pos
                    try:
                        subset = field.getSubset(**kwargs)
                    except Exception:
                        try:
                            subset = field.getSubset(region=region) if region is not None else field
                        except Exception:
                            subset = field
                    labels = list(getattr(field, 'componentLabels', ()))
                    if not header_written:
                        w.writerow(['Step','Frame','StepTime','instance','nodeLabel','elementLabel',
                                    'integrationPoint'] + (labels if labels else ['value']))
                        header_written = True
                    for v in subset.values:
                        w.writerow([step_name, frame_no, frame.frameValue,
                                    getattr(getattr(v, 'instance', None), 'name', ''),
                                    getattr(v, 'nodeLabel', ''), getattr(v, 'elementLabel', ''),
                                    getattr(v, 'integrationPoint', '')] + _as_list(v.data))
                        total += 1
        finally:
            f.close()
        summary.append([var, region_name, 'OK' if total else 'NO_DATA', total, missing_frames, out_name])

    f = _open_csv(os.path.join(WORK_DIR, 'extraction_summary.csv'))
    try:
        w = csv.writer(f)
        w.writerow(['variable','region','status','rows','missing_frames','file'])
        w.writerows(summary)
    finally:
        f.close()
except Exception:
    traceback.print_exc()
    print('ODB_EXTRACTION_FAILED')
    odb.close()
    sys.exit(1)

odb.close()
print('ODB_EXTRACTION_COMPLETE')
'''
