"""Exports for reproducibility: Jupyter notebook, full JSON transcript, Markdown report."""

from __future__ import annotations

import json
import platform
import uuid
from datetime import datetime, timezone
from typing import Any

from .agent import AgentRun
from .data import Dataset


def _package_versions() -> dict[str, str]:
    import importlib.metadata as md

    versions = {"python": platform.python_version()}
    for pkg in ("pandas", "numpy", "plotly", "scipy", "statsmodels", "scikit-learn", "matplotlib", "streamlit"):
        try:
            versions[pkg] = md.version(pkg)
        except md.PackageNotFoundError:
            pass
    return versions


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def to_json(runs: list[AgentRun], dataset: Dataset, settings: dict[str, Any] | None = None,
            system_prompt: str | None = None) -> str:
    """Complete, machine-readable record of the session (all steps, code, outputs)."""
    record = {
        "exported_at": _now(),
        "dataset": {
            "name": dataset.name,
            "sha256": dataset.sha256,
            "sheet": dataset.sheet,
            "shape": list(dataset.df.shape),
            "load_notes": dataset.notes,
        },
        "settings": settings or {},
        "environment": _package_versions(),
        "system_prompt": system_prompt,
        "runs": [r.to_dict() for r in runs],
    }
    return json.dumps(record, indent=2, default=str)


def _md_cell(text: str) -> dict:
    return {"cell_type": "markdown", "id": uuid.uuid4().hex[:12], "metadata": {},
            "source": text.splitlines(keepends=True)}


def _code_cell(code: str) -> dict:
    return {"cell_type": "code", "id": uuid.uuid4().hex[:12], "execution_count": None, "metadata": {},
            "outputs": [], "source": code.splitlines(keepends=True)}


def to_notebook(runs: list[AgentRun], dataset: Dataset, seed: int = 0) -> str:
    """A runnable notebook that replays every successful step against the same file.

    Each analysis cell starts from a fresh copy of the data with the same random seed,
    mirroring how the sandbox executed it.
    """
    sheet = repr(dataset.sheet) if dataset.sheet is not None else "None"
    cells = [
        _md_cell(
            f"# Data analysis: `{dataset.name}`\n\n"
            f"Exported {_now()} from the Data Analyst Agent.\n\n"
            f"- Dataset SHA-256: `{dataset.sha256}`\n"
            f"- Shape when analysed: {dataset.shape_text}\n"
            "- Each cell below was generated by the model and executed in the sandbox; "
            "they are replayed here verbatim.\n"
        ),
        _code_cell(
            "import hashlib\nimport random\nimport warnings\n\n"
            "import numpy as np\nimport pandas as pd\nimport plotly.express as px\n"
            "import plotly.graph_objects as go\nfrom IPython.display import Markdown, display\n\n"
            "# Same loader (encoding/delimiter detection, header cleaning) as the app.\n"
            "from analyst_agent.data import load_dataset\n\n"
            f"DATA_PATH = {dataset.name!r}  # adjust if the file lives elsewhere\n"
            f"SHEET = {sheet}\n"
            f"EXPECTED_SHA256 = {dataset.sha256!r}\n\n"
            "with open(DATA_PATH, 'rb') as fh:\n    raw = fh.read()\n"
            "if hashlib.sha256(raw).hexdigest() != EXPECTED_SHA256:\n"
            "    warnings.warn('This file differs from the one that was analysed; results may differ.')\n"
            "DATA = load_dataset(raw, DATA_PATH, sheet=SHEET).df\n\n\n"
            "def fresh_df():\n"
            "    \"\"\"Each sandbox step saw an unmodified copy of the data and a fixed seed.\"\"\"\n"
            f"    random.seed({seed})\n    np.random.seed({seed})\n    return DATA.copy()\n\n\n"
            "def show(obj, title=None):\n"
            "    if title:\n        display(Markdown(f'**{title}**'))\n"
            "    display(Markdown(obj) if isinstance(obj, str) else obj)\n"
        ),
    ]
    for n, run in enumerate(runs, 1):
        cells.append(_md_cell(f"## {n}. {run.question}"))
        for step in run.steps:
            if step.succeeded and step.code:
                header = f"# Step {step.index + 1}"
                if step.thought:
                    header += ": " + " ".join(step.thought.split())[:200]
                cells.append(_code_cell(f"{header}\ndf = fresh_df()\n{step.code}"))
        answer = run.answer or f"_No answer ({run.status}: {run.error or 'n/a'})_"
        cells.append(_md_cell(f"**Answer** ({run.status})\n\n{answer}"))

    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    return json.dumps(notebook, indent=1)


def to_markdown(runs: list[AgentRun], dataset: Dataset) -> str:
    lines = [
        f"# Analysis report: {dataset.name}",
        "",
        f"- Exported: {_now()}",
        f"- Dataset: {dataset.shape_text}, SHA-256 `{dataset.sha256[:16]}…`",
        "",
    ]
    for n, run in enumerate(runs, 1):
        lines += [f"## {n}. {run.question}", "", run.answer or f"_No answer ({run.status})._", ""]
        meta = [f"status: {run.status}", f"steps: {len(run.steps)}", f"time: {run.duration_s:.1f}s",
                f"model: {run.model}"]
        if run.grounding and run.grounding.checked:
            meta.append(f"numbers traced: {run.grounding.traced_count}/{len(run.grounding.checked)}")
        lines += [f"<sub>{' · '.join(meta)}</sub>", ""]
        code = run.successful_code
        if code:
            lines += ["<details><summary>Code</summary>", "", "```python", "\n\n".join(code), "```",
                      "", "</details>", ""]
    return "\n".join(lines)


# --------------------------------------------------------------------------- workspace sessions


def describe_tool_step(step) -> str:
    args = step.tool_args or {}
    if step.tool == "read_file":
        span = f" lines {args.get('start', 1)}-{args.get('end', 'end')}" if args.get("start") or args.get("end") else ""
        return f"read `{args.get('path', '?')}`{span}"
    if step.tool == "search":
        where = f" in `{args['glob']}`" if args.get("glob") else ""
        return f"searched for “{args.get('query', '')}”{where}"
    if step.tool == "list_files":
        return f"listed `{args.get('path', '.')}`"
    if step.tool == "propose_edits":
        paths = sorted({e.get("path", "?") for e in args.get("edits", [])})
        return "proposed changes to " + ", ".join(f"`{p}`" for p in paths)
    return f"called {step.tool}"


def workspace_to_markdown(runs: list[AgentRun], root: str) -> str:
    lines = [f"# Workspace session: {root}", "", f"- Exported: {_now()}", ""]
    for n, run in enumerate(runs, 1):
        lines += [f"## {n}. {run.question}", f"<sub>mode: {run.mode} · status: {run.status} · "
                  f"{run.duration_s:.1f}s · model: {run.model}</sub>", "", run.answer or f"_No answer ({run.status})._", ""]
        if run.citations and run.citations.citations:
            lines.append("**Sources**")
            marks = {"verified": "✔", "unseen": "?", "invalid": "✘"}
            lines += [f"- {marks.get(c.status, '')} `{c.label}` ({c.status})" for c in run.citations.citations]
            lines.append("")
        if run.changes:
            lines.append("**Proposed changes**")
            for c in run.changes:
                added, removed = c.stats()
                lines += [f"- `{c.path}` ({c.kind}, +{added} −{removed}): **{c.status}**", "",
                          "```diff", c.diff().rstrip(), "```", ""]
        steps = [s for s in run.steps if s.tool or s.code]
        if steps:
            lines += ["<details><summary>What the assistant looked at</summary>", ""]
            for s in steps:
                lines.append(f"- {describe_tool_step(s)}" if s.tool else "- ran Python:\n\n```python\n" + s.code + "\n```")
            lines += ["", "</details>", ""]
    return "\n".join(lines)


def workspace_to_json(runs: list[AgentRun], root: str, settings: dict[str, Any] | None = None,
                      system_prompt: str | None = None) -> str:
    record = {
        "exported_at": _now(),
        "workspace_root": root,
        "settings": settings or {},
        "environment": _package_versions(),
        "system_prompt": system_prompt,
        "runs": [r.to_dict() for r in runs],
    }
    return json.dumps(record, indent=2, default=str)
